---
# tasks file for deploy_docker

- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release', 'git', 'python3-pip', 'virtualenv', 'python3-setuptools' ]
  
- name: Upgrade pip
  pip:
    name: pip
    state: forcereinstall

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'docker-ce' ]
  
- name: Install Docker Module for Python
  pip:
    name: docker
    
- name: Add remote {{ ansible_user_id }} user to "docker" group
  remote_user: "{{ ansible_env.USER }}"
  user:
    name: "{{ ansible_env.USER }}"
    group: "docker"
    append: yes
