# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"
  config.vm.network "forwarded_port", guest: 8088, host: 8088
  config.vm.network "forwarded_port", guest: 22, host: 2200
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Server1"
    vb.memory = "1024"
    vb.cpus = 1
    vb.gui = false
  end
    config.vm.provision "shell", path: "scripts/init.sh"
end
